/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizzesIndexRouteImport } from './routes/quizzes/index'
import { Route as GenerateIndexRouteImport } from './routes/generate/index'
import { Route as FlashcardsIndexRouteImport } from './routes/flashcards/index'
import { Route as QuizzesQuizIdRouteImport } from './routes/quizzes/$quizId'
import { Route as FlashcardsGroupIdRouteImport } from './routes/flashcards/$groupId'
import { Route as QuizzesHistoryIndexRouteImport } from './routes/quizzes/history/index'
import { Route as FlashcardsHistoryIndexRouteImport } from './routes/flashcards/history/index'
import { Route as QuizzesHistorySessionIdRouteImport } from './routes/quizzes/history/$sessionId'
import { Route as ApiAiQuizVerifyRouteImport } from './routes/api/ai/quiz-verify'
import { Route as ApiAiContentSaveRouteImport } from './routes/api/ai/content-save'
import { Route as ApiAiContentGenerateRouteImport } from './routes/api/ai/content-generate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesIndexRoute = QuizzesIndexRouteImport.update({
  id: '/quizzes/',
  path: '/quizzes/',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateIndexRoute = GenerateIndexRouteImport.update({
  id: '/generate/',
  path: '/generate/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsIndexRoute = FlashcardsIndexRouteImport.update({
  id: '/flashcards/',
  path: '/flashcards/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesQuizIdRoute = QuizzesQuizIdRouteImport.update({
  id: '/quizzes/$quizId',
  path: '/quizzes/$quizId',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsGroupIdRoute = FlashcardsGroupIdRouteImport.update({
  id: '/flashcards/$groupId',
  path: '/flashcards/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesHistoryIndexRoute = QuizzesHistoryIndexRouteImport.update({
  id: '/quizzes/history/',
  path: '/quizzes/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsHistoryIndexRoute = FlashcardsHistoryIndexRouteImport.update({
  id: '/flashcards/history/',
  path: '/flashcards/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesHistorySessionIdRoute = QuizzesHistorySessionIdRouteImport.update({
  id: '/quizzes/history/$sessionId',
  path: '/quizzes/history/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiQuizVerifyRoute = ApiAiQuizVerifyRouteImport.update({
  id: '/api/ai/quiz-verify',
  path: '/api/ai/quiz-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiContentSaveRoute = ApiAiContentSaveRouteImport.update({
  id: '/api/ai/content-save',
  path: '/api/ai/content-save',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiContentGenerateRoute = ApiAiContentGenerateRouteImport.update({
  id: '/api/ai/content-generate',
  path: '/api/ai/content-generate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/flashcards/$groupId': typeof FlashcardsGroupIdRoute
  '/quizzes/$quizId': typeof QuizzesQuizIdRoute
  '/flashcards/': typeof FlashcardsIndexRoute
  '/generate/': typeof GenerateIndexRoute
  '/quizzes/': typeof QuizzesIndexRoute
  '/api/ai/content-generate': typeof ApiAiContentGenerateRoute
  '/api/ai/content-save': typeof ApiAiContentSaveRoute
  '/api/ai/quiz-verify': typeof ApiAiQuizVerifyRoute
  '/quizzes/history/$sessionId': typeof QuizzesHistorySessionIdRoute
  '/flashcards/history/': typeof FlashcardsHistoryIndexRoute
  '/quizzes/history/': typeof QuizzesHistoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/flashcards/$groupId': typeof FlashcardsGroupIdRoute
  '/quizzes/$quizId': typeof QuizzesQuizIdRoute
  '/flashcards': typeof FlashcardsIndexRoute
  '/generate': typeof GenerateIndexRoute
  '/quizzes': typeof QuizzesIndexRoute
  '/api/ai/content-generate': typeof ApiAiContentGenerateRoute
  '/api/ai/content-save': typeof ApiAiContentSaveRoute
  '/api/ai/quiz-verify': typeof ApiAiQuizVerifyRoute
  '/quizzes/history/$sessionId': typeof QuizzesHistorySessionIdRoute
  '/flashcards/history': typeof FlashcardsHistoryIndexRoute
  '/quizzes/history': typeof QuizzesHistoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/flashcards/$groupId': typeof FlashcardsGroupIdRoute
  '/quizzes/$quizId': typeof QuizzesQuizIdRoute
  '/flashcards/': typeof FlashcardsIndexRoute
  '/generate/': typeof GenerateIndexRoute
  '/quizzes/': typeof QuizzesIndexRoute
  '/api/ai/content-generate': typeof ApiAiContentGenerateRoute
  '/api/ai/content-save': typeof ApiAiContentSaveRoute
  '/api/ai/quiz-verify': typeof ApiAiQuizVerifyRoute
  '/quizzes/history/$sessionId': typeof QuizzesHistorySessionIdRoute
  '/flashcards/history/': typeof FlashcardsHistoryIndexRoute
  '/quizzes/history/': typeof QuizzesHistoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/flashcards/$groupId'
    | '/quizzes/$quizId'
    | '/flashcards/'
    | '/generate/'
    | '/quizzes/'
    | '/api/ai/content-generate'
    | '/api/ai/content-save'
    | '/api/ai/quiz-verify'
    | '/quizzes/history/$sessionId'
    | '/flashcards/history/'
    | '/quizzes/history/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/flashcards/$groupId'
    | '/quizzes/$quizId'
    | '/flashcards'
    | '/generate'
    | '/quizzes'
    | '/api/ai/content-generate'
    | '/api/ai/content-save'
    | '/api/ai/quiz-verify'
    | '/quizzes/history/$sessionId'
    | '/flashcards/history'
    | '/quizzes/history'
  id:
    | '__root__'
    | '/'
    | '/flashcards/$groupId'
    | '/quizzes/$quizId'
    | '/flashcards/'
    | '/generate/'
    | '/quizzes/'
    | '/api/ai/content-generate'
    | '/api/ai/content-save'
    | '/api/ai/quiz-verify'
    | '/quizzes/history/$sessionId'
    | '/flashcards/history/'
    | '/quizzes/history/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FlashcardsGroupIdRoute: typeof FlashcardsGroupIdRoute
  QuizzesQuizIdRoute: typeof QuizzesQuizIdRoute
  FlashcardsIndexRoute: typeof FlashcardsIndexRoute
  GenerateIndexRoute: typeof GenerateIndexRoute
  QuizzesIndexRoute: typeof QuizzesIndexRoute
  ApiAiContentGenerateRoute: typeof ApiAiContentGenerateRoute
  ApiAiContentSaveRoute: typeof ApiAiContentSaveRoute
  ApiAiQuizVerifyRoute: typeof ApiAiQuizVerifyRoute
  QuizzesHistorySessionIdRoute: typeof QuizzesHistorySessionIdRoute
  FlashcardsHistoryIndexRoute: typeof FlashcardsHistoryIndexRoute
  QuizzesHistoryIndexRoute: typeof QuizzesHistoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/': {
      id: '/quizzes/'
      path: '/quizzes'
      fullPath: '/quizzes/'
      preLoaderRoute: typeof QuizzesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate/': {
      id: '/generate/'
      path: '/generate'
      fullPath: '/generate/'
      preLoaderRoute: typeof GenerateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards/': {
      id: '/flashcards/'
      path: '/flashcards'
      fullPath: '/flashcards/'
      preLoaderRoute: typeof FlashcardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/$quizId': {
      id: '/quizzes/$quizId'
      path: '/quizzes/$quizId'
      fullPath: '/quizzes/$quizId'
      preLoaderRoute: typeof QuizzesQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards/$groupId': {
      id: '/flashcards/$groupId'
      path: '/flashcards/$groupId'
      fullPath: '/flashcards/$groupId'
      preLoaderRoute: typeof FlashcardsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/history/': {
      id: '/quizzes/history/'
      path: '/quizzes/history'
      fullPath: '/quizzes/history/'
      preLoaderRoute: typeof QuizzesHistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards/history/': {
      id: '/flashcards/history/'
      path: '/flashcards/history'
      fullPath: '/flashcards/history/'
      preLoaderRoute: typeof FlashcardsHistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/history/$sessionId': {
      id: '/quizzes/history/$sessionId'
      path: '/quizzes/history/$sessionId'
      fullPath: '/quizzes/history/$sessionId'
      preLoaderRoute: typeof QuizzesHistorySessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/quiz-verify': {
      id: '/api/ai/quiz-verify'
      path: '/api/ai/quiz-verify'
      fullPath: '/api/ai/quiz-verify'
      preLoaderRoute: typeof ApiAiQuizVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/content-save': {
      id: '/api/ai/content-save'
      path: '/api/ai/content-save'
      fullPath: '/api/ai/content-save'
      preLoaderRoute: typeof ApiAiContentSaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/content-generate': {
      id: '/api/ai/content-generate'
      path: '/api/ai/content-generate'
      fullPath: '/api/ai/content-generate'
      preLoaderRoute: typeof ApiAiContentGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FlashcardsGroupIdRoute: FlashcardsGroupIdRoute,
  QuizzesQuizIdRoute: QuizzesQuizIdRoute,
  FlashcardsIndexRoute: FlashcardsIndexRoute,
  GenerateIndexRoute: GenerateIndexRoute,
  QuizzesIndexRoute: QuizzesIndexRoute,
  ApiAiContentGenerateRoute: ApiAiContentGenerateRoute,
  ApiAiContentSaveRoute: ApiAiContentSaveRoute,
  ApiAiQuizVerifyRoute: ApiAiQuizVerifyRoute,
  QuizzesHistorySessionIdRoute: QuizzesHistorySessionIdRoute,
  FlashcardsHistoryIndexRoute: FlashcardsHistoryIndexRoute,
  QuizzesHistoryIndexRoute: QuizzesHistoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
